export type RevealNight = {
  nightLabel: string;
  nightOrdinal: string;
  question: string;
  topSong: string;
  topArtist: string;
  topArt: string;
  consensusPct: number;
  totalVotes: number;
  wordCloud: { word: string; size: 'xl' | 'lg' | 'md' | 'sm' }[];
  tomorrowTeaser: string;
};

export const REVEAL_NIGHTS: RevealNight[] = [
  {
    nightLabel: 'Night one · the reveal',
    nightOrdinal: 'one',
    question: 'What song would play first at a Hoya house party right now?',
    topSong: 'Not Like Us',
    topArtist: 'Kendrick Lamar',
    topArt: '/artists/kendrick.png',
    consensusPct: 38,
    totalVotes: 1204,
    wordCloud: [
      { word: 'Not Like Us', size: 'xl' },
      { word: 'Espresso', size: 'lg' },
      { word: 'HUMBLE.', size: 'lg' },
      { word: 'luther', size: 'md' },
      { word: 'Blinding Lights', size: 'md' },
      { word: 'Starboy', size: 'sm' },
      { word: 'Good 4 U', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: The most iconic chorus of the last 5 years?',
  },
  {
    nightLabel: 'Night two · the reveal',
    nightOrdinal: 'two',
    question: 'If Georgetown had an anthem, what song would it be?',
    topSong: 'Espresso',
    topArtist: 'Sabrina Carpenter',
    topArt: '/artists/sabrina.png',
    consensusPct: 31,
    totalVotes: 1186,
    wordCloud: [
      { word: 'Espresso', size: 'xl' },
      { word: 'Good 4 U', size: 'lg' },
      { word: 'Anti-Hero', size: 'lg' },
      { word: 'Cruel Summer', size: 'md' },
      { word: 'luther', size: 'md' },
      { word: 'Not Like Us', size: 'sm' },
      { word: 'Flowers', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: Best study-session album of all time?',
  },
  {
    nightLabel: 'Night three · the reveal',
    nightOrdinal: 'three',
    question: 'Which Taylor Swift era are Hoyas living in right now?',
    topSong: 'Cruel Summer',
    topArtist: 'Taylor Swift',
    topArt: '/artists/taylor.png',
    consensusPct: 44,
    totalVotes: 1312,
    wordCloud: [
      { word: 'Lover', size: 'xl' },
      { word: 'Midnights', size: 'lg' },
      { word: 'Folklore', size: 'lg' },
      { word: '1989', size: 'md' },
      { word: 'Eras', size: 'md' },
      { word: 'Red', size: 'sm' },
      { word: 'Fearless', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: The song that hits different at 2am?',
  },
  {
    nightLabel: 'Night four · the reveal',
    nightOrdinal: 'four',
    question: 'What\'s the most overplayed song that\'s still a banger?',
    topSong: 'Blinding Lights',
    topArtist: 'The Weeknd',
    topArt: '/artists/billie.png',
    consensusPct: 27,
    totalVotes: 1099,
    wordCloud: [
      { word: 'Blinding Lights', size: 'xl' },
      { word: 'Levitating', size: 'lg' },
      { word: 'Watermelon Sugar', size: 'lg' },
      { word: 'Industry Baby', size: 'md' },
      { word: 'drivers license', size: 'md' },
      { word: 'Savage Love', size: 'sm' },
      { word: 'Stay', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: Best rap album of the 2020s so far?',
  },
  {
    nightLabel: 'Night five · the reveal',
    nightOrdinal: 'five',
    question: 'The song that defined your freshman year?',
    topSong: 'good 4 u',
    topArtist: 'Olivia Rodrigo',
    topArt: '/artists/billie.png',
    consensusPct: 29,
    totalVotes: 1158,
    wordCloud: [
      { word: 'good 4 u', size: 'xl' },
      { word: 'drivers license', size: 'lg' },
      { word: 'Montero', size: 'lg' },
      { word: 'Kiss Me More', size: 'md' },
      { word: 'Butter', size: 'md' },
      { word: 'Peaches', size: 'sm' },
      { word: 'MONTERO', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: The hardest Kendrick verse of all time?',
  },
  {
    nightLabel: 'Night six · the reveal',
    nightOrdinal: 'six',
    question: 'What\'s the song you could listen to 100 times and never skip?',
    topSong: 'Self Control',
    topArtist: 'Frank Ocean',
    topArt: '/artists/frank-blond.png',
    consensusPct: 22,
    totalVotes: 1021,
    wordCloud: [
      { word: 'Self Control', size: 'xl' },
      { word: 'Pyramids', size: 'lg' },
      { word: 'Pink + White', size: 'lg' },
      { word: 'Good Days', size: 'md' },
      { word: 'Die For You', size: 'md' },
      { word: 'Saturn', size: 'sm' },
      { word: 'Murder On The Dancefloor', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: Best debut album in music history?',
  },
  {
    nightLabel: 'Night seven · the reveal',
    nightOrdinal: 'seven',
    question: 'If you could only listen to one album for a month, what is it?',
    topSong: 'SOS',
    topArtist: 'SZA',
    topArt: '/artists/sza-saturn.png',
    consensusPct: 33,
    totalVotes: 1267,
    wordCloud: [
      { word: 'SOS', size: 'xl' },
      { word: 'CTRL', size: 'lg' },
      { word: 'Blonde', size: 'lg' },
      { word: 'DAMN.', size: 'md' },
      { word: 'folklore', size: 'md' },
      { word: 'GNX', size: 'sm' },
      { word: 'Sour', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: The song playing when the party peaks?',
  },
  {
    nightLabel: 'Night eight · the reveal',
    nightOrdinal: 'eight',
    question: 'The most iconic music video ever made?',
    topSong: 'Bad Guy',
    topArtist: 'Billie Eilish',
    topArt: '/artists/billie.png',
    consensusPct: 24,
    totalVotes: 1144,
    wordCloud: [
      { word: 'bad guy', size: 'xl' },
      { word: 'Telephone', size: 'lg' },
      { word: 'Thriller', size: 'lg' },
      { word: 'Formation', size: 'md' },
      { word: 'HUMBLE.', size: 'md' },
      { word: 'Sicko Mode', size: 'sm' },
      { word: 'Royals', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: The last song you\'d want played at your funeral?',
  },
  {
    nightLabel: 'Night nine · the reveal',
    nightOrdinal: 'nine',
    question: 'Best Chappell Roan song to play at sunrise on the steps?',
    topSong: 'Good Luck, Babe!',
    topArtist: 'Chappell Roan',
    topArt: '/artists/chappell.png',
    consensusPct: 36,
    totalVotes: 1198,
    wordCloud: [
      { word: 'Good Luck, Babe!', size: 'xl' },
      { word: 'Red Wine Supernova', size: 'lg' },
      { word: 'Hot To Go!', size: 'lg' },
      { word: 'Femininomenon', size: 'md' },
      { word: 'Pink Pony Club', size: 'md' },
      { word: 'Super Graphic', size: 'sm' },
      { word: 'California', size: 'sm' },
    ],
    tomorrowTeaser: 'Tomorrow: Night ten — the big one. What song defined this year?',
  },
  {
    nightLabel: 'Night ten · the reveal',
    nightOrdinal: 'ten',
    question: 'What\'s the song of the year for Georgetown?',
    topSong: 'luther',
    topArtist: 'Kendrick Lamar & SZA',
    topArt: '/artists/kendrick.png',
    consensusPct: 42,
    totalVotes: 1388,
    wordCloud: [
      { word: 'luther', size: 'xl' },
      { word: 'Not Like Us', size: 'lg' },
      { word: 'Espresso', size: 'lg' },
      { word: 'Good Luck, Babe!', size: 'md' },
      { word: 'Self Control', size: 'md' },
      { word: 'Saturn', size: 'sm' },
      { word: 'Cruel Summer', size: 'sm' },
    ],
    tomorrowTeaser: 'A new question drops tomorrow. See you at 8pm.',
  },
];

export function getRevealNight(dayIndex: number): RevealNight {
  return REVEAL_NIGHTS[((dayIndex % 10) + 10) % 10];
}
